#!/bin/bash

DATA_DIR="`dirname "$0"`/../kantan-data"
DATA_DIR_LENGTH=${#DATA_DIR}+1

kantan_create()
{
  #TODO open new file in insert mode and without newline
  date=`date +'%Y%m%d'`
  kantan_open "$date-${1// /-}"
  kantan_list
}

kantan_open()
{
  filename="$DATA_DIR/${1// /-}.txt"
  vim +'normal G$o' $filename < `tty` > `tty`
  ex +'%s#\s\+$##' +'%s#\n\+\%$##' +'wq' $filename
}

kantan_list()
{
  unset options i
  for file in $(find $DATA_DIR/* -type f | sort --numeric-sort)
  do
    option="${file:$DATA_DIR_LENGTH}"
    option="${option//-/ }"
    options[i++]="${option//.txt/}"
  done

  PS3="Open (#), quit (q) or create with title: "
  select option in "${options[@]}"
  do
    case $REPLY in
      *[!0-9]*)
        if [[ "$REPLY" == "q" ]]
          then
            break
          fi
          kantan_create "$REPLY"
        ;;
      *)
        if [[ "$option" != "" ]]
          then
            kantan_open "$option"
          else
            echo "No option ${REPLY}."
        fi
        ;;
    esac
  done
}

kantan_list