#!/bin/bash

DATA_DIR="`dirname "$0"`/../kantan-data"
DATA_DIR_LENGTH=${#DATA_DIR}+1

kantan_create()
{
  read -p "Subject: " subject
  date=`date +'%Y%m%d'`
  kantan_open "$date-${subject// /-}"
}

kantan_open()
{
  filename="$DATA_DIR/$1"
  vim +'normal G$o' $filename < `tty` > `tty`
  ex +'%s#\s\+$##' +'%s#\n\+\%$##' +'wq' $filename
}

kantan_list()
{
  unset options i
  while IFS= read -r -d $'\0' f; do
    #TODO: improve filename in list view
    options[i++]="${f:$DATA_DIR_LENGTH}"
  done < <(find $DATA_DIR -maxdepth 1 -type f -name '*.txt' -print0 )

  select opt in "Quit" "New" "${options[@]}"; do
    case $opt in
      *.txt)
        kantan_open "$opt"
        ;;
      "New")
        kantan_create
        ;;
      "Quit")
        break
        ;;
      *)
        ;;
    esac
  done
}

kantan_list